In [1]:
import numpy as np

In [3]:
mylist=[1,2,3]


In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
list

list

In [8]:
print(mylist)

[1, 2, 3]


In [9]:
myarray = np.array(mylist)

In [11]:
myarray

array([1, 2, 3])

In [12]:
type(myarray)

numpy.ndarray

In [13]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(np.arange(0,11,2))
print(np.arange(10,28,3))

[ 0  2  4  6  8 10]
[10 13 16 19 22 25]


In [31]:
np.zeros(((3,5,5)))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [41]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.linspace(0,100,5 ,2)

array([  0.,  25.,  50.,  75., 100.])